/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from "react";
import { UserRole, UserProfile } from "../types";
import { 
  ShieldCheck, 
  Mail, 
  Lock, 
  User, 
  Briefcase, 
  Building2, 
  Check, 
  ArrowRight, 
  Key, 
  Sparkles,
  Info,
  X
} from "lucide-react";
import LandingHero from "./LandingHero";

interface AuthScreenProps {
  onAuthSuccess: (user: UserProfile) => void;
}

export default function AuthScreen(props: AuthScreenProps) {
  const [showAuthModal, setShowAuthModal] = useState(false);
  const [isLogin, setIsLogin] = useState(true);
  const [role, setRole] = useState<UserRole>(UserRole.CANDIDATE);
  const [email, setEmail] = useState("");
  const [fullName, setFullName] = useState("");
  const [companyName, setCompanyName] = useState("");
  const [password, setPassword] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  
  // MFA States
  const [mfaPending, setMfaPending] = useState(false);
  const [mfaUserId, setMfaUserId] = useState("");
  const [mfaCode, setMfaCode] = useState("");

  const handleAuth = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError(null);

    const endpoint = isLogin ? "/api/auth/login" : "/api/auth/register";
    const body = isLogin 
      ? { email, password } 
      : { email, password, fullName, role, companyName };

    try {
      const res = await fetch(endpoint, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body)
      });
      const data = await res.json();

      if (!res.ok) {
        throw new Error(data.error || "Authentication failed. Please verify inputs.");
      }

      if (isLogin && data.requiresMfa) {
        setMfaPending(true);
        setMfaUserId(data.user.id);
        setLoading(false);
        return;
      }

      // No MFA needed or registration completed
      props.onAuthSuccess(data.user);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleMfaSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError(null);

    try {
      const res = await fetch("/api/auth/mfa-verify", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ userId: mfaUserId, code: mfaCode })
      });
      const data = await res.json();

      if (!res.ok) {
        throw new Error(data.error || "Invalid verification code.");
      }

      props.onAuthSuccess(data.user);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const loadDemoUser = async (demoRole: UserRole) => {
    setLoading(true);
    setError(null);
    let demoEmail = "";
    if (demoRole === UserRole.CANDIDATE) demoEmail = "candidate@saas.com";
    if (demoRole === UserRole.RECRUITER) demoEmail = "recruiter@saas.com";
    if (demoRole === UserRole.ADMIN) demoEmail = "admin@saas.com";

    try {
      const res = await fetch("/api/auth/login", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email: demoEmail, password: "demo" })
      });
      const data = await res.json();

      if (!res.ok) {
        throw new Error(data.error);
      }

      if (data.requiresMfa) {
        setMfaPending(true);
        setMfaUserId(data.user.id);
        setLoading(false);
        return;
      }

      props.onAuthSuccess(data.user);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  if (mfaPending) {
    return (
      <div className="min-h-screen bg-slate-950 flex flex-col items-center justify-center p-4 font-sans text-slate-100 relative overflow-hidden" id="mfa-screen-wrapper">
        <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-indigo-500/[0.04] rounded-full blur-3xl animate-pulse"></div>
        <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-emerald-500/[0.03] rounded-full blur-3xl"></div>
        
        <div className="w-full max-w-sm bg-slate-900 border border-slate-850 rounded-xl p-6 shadow-2xl relative z-10" id="mfa-container">
          <div className="flex justify-center mb-4">
            <div className="p-2.5 bg-emerald-500/10 rounded-lg border border-emerald-500/20 text-emerald-400">
              <ShieldCheck className="w-6 h-6" />
            </div>
          </div>

          <h2 className="text-lg font-bold font-sans tracking-tight text-center text-white mb-1" id="mfa-title">
            Two-Step Verification
          </h2>
          <p className="text-slate-400 text-xs text-center mb-4" id="mfa-desc">
            A high-security verification request has been logged. Enter the 6-digit credential code generated by your MFA authenticator.
          </p>

          <form onSubmit={handleMfaSubmit} className="space-y-4" id="mfa-form">
            {error && (
              <div className="p-2.5 bg-rose-500/10 border border-rose-500/20 rounded-lg text-rose-400 text-xs flex items-start gap-2" id="mfa-error">
                <Info className="w-3.5 h-3.5 mt-0.5 flex-shrink-0" />
                <span>{error}</span>
              </div>
            )}

            <div>
              <label className="block text-[11px] font-semibold text-slate-500 uppercase tracking-wider mb-1">
                Authentication Pin
              </label>
              <div className="relative">
                <Key className="absolute left-3 top-2.5 w-4 h-4 text-slate-400" />
                <input
                  type="text"
                  placeholder="e.g. 123456"
                  required
                  value={mfaCode}
                  onChange={(e) => setMfaCode(e.target.value)}
                  className="w-full pl-9 pr-3 py-1.5 bg-slate-950 border border-slate-800 focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500/20 rounded-lg text-white placeholder-slate-600 transition outline-none text-center font-mono tracking-widest text-sm"
                  id="mfa-input"
                />
              </div>
              <p className="text-[11px] text-slate-500 mt-1.5 text-center">
                *Demo Bypass: Enter any numbers to continue.
              </p>
            </div>

            <button
              type="submit"
              disabled={loading}
              className="w-full py-2 bg-indigo-600 hover:bg-indigo-700 active:bg-indigo-800 disabled:opacity-50 text-white font-semibold rounded-lg transition flex items-center justify-center gap-1.5 cursor-pointer text-xs"
              id="mfa-verify-btn"
            >
              {loading ? "Verifying..." : "Validate Credentials"}
              <ArrowRight className="w-3.5 h-3.5" />
            </button>
          </form>
        </div>
      </div>
    );
  }

  return (
    <div className="relative min-h-screen" id="auth-root-container">
      {/* 1. Stunning Landing Hero Background */}
      <LandingHero 
        onGetStarted={() => {
          setIsLogin(false);
          setShowAuthModal(true);
          setError(null);
        }}
        onLoginClick={() => {
          setIsLogin(true);
          setShowAuthModal(true);
          setError(null);
        }}
        onDemoCandidate={() => loadDemoUser(UserRole.CANDIDATE)}
        onDemoRecruiter={() => loadDemoUser(UserRole.RECRUITER)}
        onDemoAdmin={() => loadDemoUser(UserRole.ADMIN)}
      />

      {/* 2. Glassmorphic Modal Dialog Overlay for Credentials */}
      {showAuthModal && (
        <div className="fixed inset-0 bg-slate-950/80 backdrop-blur-md flex items-center justify-center p-4 z-50 animate-fade-in" id="auth-modal-overlay">
          <div className="w-full max-w-md bg-slate-900/90 border border-slate-800 rounded-2xl p-6 shadow-[0_25px_60px_-15px_rgba(0,0,0,0.7)] relative z-10" id="form-container">
            
            {/* Close Button */}
            <button 
              onClick={() => setShowAuthModal(false)}
              className="absolute top-4 right-4 p-1 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition cursor-pointer"
              id="close-modal-btn"
            >
              <X className="w-5 h-5" />
            </button>

            {/* Logo and Identity */}
            <div className="flex items-center gap-2 mb-4">
              <div className="w-8 h-8 bg-indigo-600/10 border border-indigo-500/20 rounded-lg flex items-center justify-center text-indigo-400">
                <ShieldCheck className="w-4.5 h-4.5" />
              </div>
              <div>
                <span className="font-bold tracking-tight text-white block text-xs leading-none">TechScreen SaaS</span>
                <span className="text-[9px] text-slate-500 font-mono tracking-wider">SECURE ACCESS GATEWAY</span>
              </div>
            </div>

            {/* Sliding Tab Triggers */}
            <div className="flex bg-slate-950 p-1 rounded-lg border border-slate-800 mb-4" id="auth-tab-triggers">
              <button
                type="button"
                onClick={() => { setIsLogin(true); setError(null); }}
                className={`flex-1 py-1.5 rounded-md text-xs font-semibold transition cursor-pointer ${isLogin ? "bg-slate-800 text-white font-bold" : "text-slate-500 hover:text-slate-300"}`}
                id="tab-login"
              >
                Sign In
              </button>
              <button
                type="button"
                onClick={() => { setIsLogin(false); setError(null); }}
                className={`flex-1 py-1.5 rounded-md text-xs font-semibold transition cursor-pointer ${!isLogin ? "bg-slate-800 text-white font-bold" : "text-slate-500 hover:text-slate-300"}`}
                id="tab-register"
              >
                Create Account
              </button>
            </div>

            <form onSubmit={handleAuth} className="space-y-3.5" id="credentials-form">
              {error && (
                <div className="p-2.5 bg-rose-500/10 border border-rose-500/20 rounded-lg text-rose-400 text-xs flex items-start gap-2" id="credentials-error">
                  <Info className="w-3.5 h-3.5 mt-0.5 flex-shrink-0" />
                  <span>{error}</span>
                </div>
              )}

              {/* Dynamic Registration Fields */}
              {!isLogin && (
                <>
                  <div>
                    <label className="block text-[11px] font-semibold text-slate-400 uppercase tracking-wider mb-1">
                      Full Name
                    </label>
                    <div className="relative">
                      <User className="absolute left-3 top-2.5 w-4 h-4 text-slate-500" />
                      <input
                        type="text"
                        placeholder="John Doe"
                        required
                        value={fullName}
                        onChange={(e) => setFullName(e.target.value)}
                        className="w-full pl-9 pr-3 py-1.5 bg-slate-950 border border-slate-800 focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500/20 rounded-lg text-white placeholder-slate-600 transition outline-none text-xs"
                        id="reg-fullname"
                      />
                    </div>
                  </div>

                  <div>
                    <label className="block text-[11px] font-semibold text-slate-400 uppercase tracking-wider mb-1">
                      Registering As
                    </label>
                    <div className="grid grid-cols-2 gap-2" id="role-selector">
                      <button
                        type="button"
                        onClick={() => setRole(UserRole.CANDIDATE)}
                        className={`py-1.5 px-3 border rounded-lg text-xs font-semibold flex items-center justify-center gap-1.5 transition cursor-pointer ${role === UserRole.CANDIDATE ? "border-indigo-500 bg-indigo-500/10 text-indigo-300" : "border-slate-800 bg-slate-950 text-slate-500 hover:text-slate-300"}`}
                        id="role-cand-trigger"
                      >
                        <User className="w-3.5 h-3.5" />
                        <span>Candidate</span>
                      </button>
                      <button
                        type="button"
                        onClick={() => setRole(UserRole.RECRUITER)}
                        className={`py-1.5 px-3 border rounded-lg text-xs font-semibold flex items-center justify-center gap-1.5 transition cursor-pointer ${role === UserRole.RECRUITER ? "border-indigo-500 bg-indigo-500/10 text-indigo-300" : "border-slate-800 bg-slate-950 text-slate-500 hover:text-slate-300"}`}
                        id="role-rec-trigger"
                      >
                        <Briefcase className="w-3.5 h-3.5" />
                        <span>Recruiter</span>
                      </button>
                    </div>
                  </div>

                  {role === UserRole.RECRUITER && (
                    <div>
                      <label className="block text-[11px] font-semibold text-slate-400 uppercase tracking-wider mb-1">
                        Company Name
                      </label>
                      <div className="relative">
                        <Building2 className="absolute left-3 top-2.5 w-4 h-4 text-slate-500" />
                        <input
                          type="text"
                          placeholder="e.g. Acme Tech Labs"
                          required
                          value={companyName}
                          onChange={(e) => setCompanyName(e.target.value)}
                          className="w-full pl-9 pr-3 py-1.5 bg-slate-950 border border-slate-800 focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500/20 rounded-lg text-white placeholder-slate-600 transition outline-none text-xs"
                          id="reg-company"
                        />
                      </div>
                    </div>
                  )}
                </>
              )}

              <div>
                <label className="block text-[11px] font-semibold text-slate-400 uppercase tracking-wider mb-1">
                  Email Address
                </label>
                <div className="relative">
                  <Mail className="absolute left-3 top-2.5 w-4 h-4 text-slate-500" />
                  <input
                     type="email"
                     placeholder="you@example.com"
                     required
                     value={email}
                     onChange={(e) => setEmail(e.target.value)}
                     className="w-full pl-9 pr-3 py-1.5 bg-slate-950 border border-slate-800 focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500/20 rounded-lg text-white placeholder-slate-600 transition outline-none text-xs"
                     id="credentials-email"
                  />
                </div>
              </div>

              <div>
                <label className="block text-[11px] font-semibold text-slate-400 uppercase tracking-wider mb-1">
                  Password
                </label>
                <div className="relative">
                  <Lock className="absolute left-3 top-2.5 w-4 h-4 text-slate-500" />
                  <input
                    type="password"
                    placeholder="••••••••"
                    required
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    className="w-full pl-9 pr-3 py-1.5 bg-slate-950 border border-slate-800 focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500/20 rounded-lg text-white placeholder-slate-600 transition outline-none text-xs"
                    id="credentials-pass"
                  />
                </div>
              </div>

              <button
                type="submit"
                disabled={loading}
                className="w-full py-2 bg-indigo-600 hover:bg-indigo-500 active:bg-indigo-700 disabled:opacity-50 text-white font-bold rounded-lg transition cursor-pointer text-xs mt-3 shadow-md"
                id="submit-auth-btn"
              >
                {loading ? "Authenticating Session..." : isLogin ? "Access Portal Dashboard" : "Register and Continue"}
              </button>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}

