/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from "react";
import { UserRole, UserProfile } from "../types";
import { 
  ShieldCheck, 
  Mail, 
  Lock, 
  User, 
  Briefcase, 
  Building2, 
  Check, 
  ArrowRight, 
  Key, 
  Sparkles,
  Info
} from "lucide-react";

interface AuthScreenProps {
  onAuthSuccess: (user: UserProfile) => void;
}

export default function AuthScreen(props: AuthScreenProps) {
  const [isLogin, setIsLogin] = useState(true);
  const [role, setRole] = useState<UserRole>(UserRole.CANDIDATE);
  const [email, setEmail] = useState("");
  const [fullName, setFullName] = useState("");
  const [companyName, setCompanyName] = useState("");
  const [password, setPassword] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  
  // MFA States
  const [mfaPending, setMfaPending] = useState(false);
  const [mfaUserId, setMfaUserId] = useState("");
  const [mfaCode, setMfaCode] = useState("");

  const handleAuth = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError(null);

    const endpoint = isLogin ? "/api/auth/login" : "/api/auth/register";
    const body = isLogin 
      ? { email, password } 
      : { email, password, fullName, role, companyName };

    try {
      const res = await fetch(endpoint, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body)
      });
      const data = await res.json();

      if (!res.ok) {
        throw new Error(data.error || "Authentication failed. Please verify inputs.");
      }

      if (isLogin && data.requiresMfa) {
        setMfaPending(true);
        setMfaUserId(data.user.id);
        setLoading(false);
        return;
      }

      // No MFA needed or registration completed
      props.onAuthSuccess(data.user);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleMfaSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError(null);

    try {
      const res = await fetch("/api/auth/mfa-verify", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ userId: mfaUserId, code: mfaCode })
      });
      const data = await res.json();

      if (!res.ok) {
        throw new Error(data.error || "Invalid verification code.");
      }

      props.onAuthSuccess(data.user);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const loadDemoUser = async (demoRole: UserRole) => {
    setLoading(true);
    setError(null);
    let demoEmail = "";
    if (demoRole === UserRole.CANDIDATE) demoEmail = "candidate@saas.com";
    if (demoRole === UserRole.RECRUITER) demoEmail = "recruiter@saas.com";
    if (demoRole === UserRole.ADMIN) demoEmail = "admin@saas.com";

    try {
      const res = await fetch("/api/auth/login", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email: demoEmail, password: "demo" })
      });
      const data = await res.json();

      if (!res.ok) {
        throw new Error(data.error);
      }

      if (data.requiresMfa) {
        setMfaPending(true);
        setMfaUserId(data.user.id);
        setLoading(false);
        return;
      }

      props.onAuthSuccess(data.user);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  if (mfaPending) {
    return (
      <div className="min-h-screen bg-slate-50 flex flex-col items-center justify-center p-4 font-sans text-slate-900 relative overflow-hidden" id="mfa-screen-wrapper">
        <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-indigo-500/[0.02] rounded-full blur-3xl"></div>
        <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-emerald-500/[0.02] rounded-full blur-3xl"></div>
        
        <div className="w-full max-w-sm bg-white border border-slate-200 rounded-xl p-6 shadow-sm relative z-10" id="mfa-container">
          <div className="flex justify-center mb-4">
            <div className="p-2.5 bg-emerald-50 rounded-lg border border-emerald-200 text-emerald-700">
              <ShieldCheck className="w-6 h-6" />
            </div>
          </div>

          <h2 className="text-lg font-bold font-sans tracking-tight text-center text-slate-900 mb-1" id="mfa-title">
            Two-Step Verification
          </h2>
          <p className="text-slate-500 text-xs text-center mb-4" id="mfa-desc">
            A high-security verification request has been logged. Enter the 6-digit credential code generated by your MFA authenticator.
          </p>

          <form onSubmit={handleMfaSubmit} className="space-y-4" id="mfa-form">
            {error && (
              <div className="p-2.5 bg-rose-50 border border-rose-200 rounded-lg text-rose-700 text-xs flex items-start gap-2" id="mfa-error">
                <Info className="w-3.5 h-3.5 mt-0.5 flex-shrink-0" />
                <span>{error}</span>
              </div>
            )}

            <div>
              <label className="block text-[11px] font-semibold text-slate-500 uppercase tracking-wider mb-1">
                Authentication Pin
              </label>
              <div className="relative">
                <Key className="absolute left-3 top-2.5 w-4 h-4 text-slate-400" />
                <input
                  type="text"
                  placeholder="e.g. 123456"
                  required
                  value={mfaCode}
                  onChange={(e) => setMfaCode(e.target.value)}
                  className="w-full pl-9 pr-3 py-1.5 bg-slate-50 border border-slate-200 focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500/20 rounded-lg text-slate-900 placeholder-slate-400 transition outline-none text-center font-mono tracking-widest text-sm"
                  id="mfa-input"
                />
              </div>
              <p className="text-[11px] text-slate-400 mt-1.5 text-center">
                *Demo Bypass: Enter any numbers to continue.
              </p>
            </div>

            <button
              type="submit"
              disabled={loading}
              className="w-full py-2 bg-indigo-600 hover:bg-indigo-700 active:bg-indigo-800 disabled:opacity-50 text-white font-semibold rounded-lg transition flex items-center justify-center gap-1.5 cursor-pointer text-xs"
              id="mfa-verify-btn"
            >
              {loading ? "Verifying..." : "Validate Credentials"}
              <ArrowRight className="w-3.5 h-3.5" />
            </button>
          </form>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-50 flex flex-col font-sans text-slate-800 relative overflow-hidden" id="auth-screen-wrapper">
      {/* Dynamic Background Accents */}
      <div className="absolute top-0 left-0 w-full h-full bg-[radial-gradient(circle_at_50%_0%,rgba(99,102,241,0.03),transparent_50%)]"></div>
      <div className="absolute -top-40 -left-40 w-96 h-96 bg-indigo-500/[0.01] rounded-full blur-3xl"></div>
      <div className="absolute -bottom-40 -right-40 w-96 h-96 bg-emerald-500/[0.01] rounded-full blur-3xl"></div>

      {/* Header */}
      <header className="w-full bg-white border-b border-slate-200 px-6 py-3.5 relative z-10" id="auth-header">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 bg-indigo-50 border border-indigo-100 rounded-lg flex items-center justify-center text-indigo-600">
              <ShieldCheck className="w-4.5 h-4.5" />
            </div>
            <div>
              <span className="font-bold tracking-tight text-slate-900 block text-sm leading-none">TechScreen</span>
              <span className="text-[9px] text-indigo-600 font-mono tracking-wider uppercase font-semibold">SaaS Competency</span>
            </div>
          </div>
          <div className="flex items-center gap-2 text-[11px] text-slate-500 bg-slate-50 border border-slate-200 px-2.5 py-1 rounded-full">
            <span className="w-1.5 h-1.5 bg-emerald-500 rounded-full animate-pulse"></span>
            <span>SOC 2 Verified</span>
          </div>
        </div>
      </header>

      {/* Main Grid Content */}
      <main className="flex-grow max-w-7xl mx-auto px-6 py-8 grid grid-cols-1 lg:grid-cols-12 gap-8 items-center relative z-10 w-full" id="auth-main">
        {/* Left column: Brand pitch */}
        <div className="lg:col-span-7 space-y-5" id="auth-pitch-col">
          <div className="inline-flex items-center gap-1.5 px-2 py-0.5 bg-indigo-50 border border-indigo-100 text-indigo-700 rounded-full text-[11px] font-semibold">
            <Sparkles className="w-3 h-3" />
            <span>Trusted Competency Hub</span>
          </div>

          <h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight text-slate-900 leading-tight">
            Standardize and Automate <br />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-600 to-indigo-800">
              Technical Competency
            </span>
          </h1>

          <p className="text-slate-500 text-[13px] max-w-xl leading-relaxed">
            Standardize your organization's recruitment workflow. Implement dynamic coding challenges, strict browser proctoring, and comprehensive Gemini-assisted code reports.
          </p>

          {/* Core modules quick checklist */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 max-w-xl pt-2" id="features-highlights">
            {[
              "Automated Code Review Engine",
              "Balanced Test Generation Bank",
              "Digital Validity Certificates",
              "Multi-Language Code Sandbox",
              "Dynamic Proctor Monitoring",
              "Recruiter Comparison Analytics"
            ].map((text, idx) => (
              <div key={idx} className="flex items-center gap-2.5 text-slate-600">
                <div className="w-4.5 h-4.5 bg-indigo-50 border border-indigo-150 text-indigo-600 rounded-full flex items-center justify-center flex-shrink-0">
                  <Check className="w-2.5 h-2.5" />
                </div>
                <span className="text-xs font-medium">{text}</span>
              </div>
            ))}
          </div>

          {/* Quick Demo bypass triggers */}
          <div className="pt-4 border-t border-slate-200 max-w-xl" id="demo-bypass-panel">
            <span className="text-[10px] text-slate-400 block mb-2 font-semibold uppercase tracking-wider">
              Explore Immediately (Demo Quick Access):
            </span>
            <div className="flex flex-wrap gap-2">
              <button 
                onClick={() => loadDemoUser(UserRole.CANDIDATE)}
                className="px-2.5 py-1.5 bg-white hover:bg-slate-50 border border-slate-200 text-slate-600 rounded-lg text-xs font-semibold flex items-center gap-1.5 cursor-pointer transition-colors"
                id="demo-candidate-btn"
              >
                <User className="w-3.5 h-3.5 text-indigo-500" />
                <span>Candidate Portal</span>
              </button>
              <button 
                onClick={() => loadDemoUser(UserRole.RECRUITER)}
                className="px-2.5 py-1.5 bg-white hover:bg-slate-50 border border-slate-200 text-slate-600 rounded-lg text-xs font-semibold flex items-center gap-1.5 cursor-pointer transition-colors"
                id="demo-recruiter-btn"
              >
                <Briefcase className="w-3.5 h-3.5 text-indigo-500" />
                <span>Recruiter Console</span>
              </button>
              <button 
                onClick={() => loadDemoUser(UserRole.ADMIN)}
                className="px-2.5 py-1.5 bg-white hover:bg-slate-50 border border-slate-200 text-slate-600 rounded-lg text-xs font-semibold flex items-center gap-1.5 cursor-pointer transition-colors"
                id="demo-admin-btn"
              >
                <ShieldCheck className="w-3.5 h-3.5 text-emerald-600" />
                <span>Platform Admin</span>
              </button>
            </div>
          </div>
        </div>

        {/* Right column: Form */}
        <div className="lg:col-span-5" id="auth-form-col">
          <div className="bg-white border border-slate-200 rounded-xl p-6 shadow-sm" id="form-container">
            <div className="flex bg-slate-50 p-1 rounded-lg border border-slate-200 mb-4" id="auth-tab-triggers">
              <button
                type="button"
                onClick={() => { setIsLogin(true); setError(null); }}
                className={`flex-1 py-1.5 rounded-md text-xs font-semibold transition cursor-pointer ${isLogin ? "bg-white border border-slate-200/60 shadow-xs text-slate-900 font-bold" : "text-slate-500 hover:text-slate-900"}`}
                id="tab-login"
              >
                Sign In
              </button>
              <button
                type="button"
                onClick={() => { setIsLogin(false); setError(null); }}
                className={`flex-1 py-1.5 rounded-md text-xs font-semibold transition cursor-pointer ${!isLogin ? "bg-white border border-slate-200/60 shadow-xs text-slate-900 font-bold" : "text-slate-500 hover:text-slate-900"}`}
                id="tab-register"
              >
                Create Account
              </button>
            </div>

            <form onSubmit={handleAuth} className="space-y-3.5" id="credentials-form">
              {error && (
                <div className="p-2.5 bg-rose-50 border border-rose-200 rounded-lg text-rose-700 text-xs flex items-start gap-2" id="credentials-error">
                  <Info className="w-3.5 h-3.5 mt-0.5 flex-shrink-0" />
                  <span>{error}</span>
                </div>
              )}

              {/* Dynamic Registration Fields */}
              {!isLogin && (
                <>
                  <div>
                    <label className="block text-[11px] font-semibold text-slate-500 uppercase tracking-wider mb-1">
                      Full Name
                    </label>
                    <div className="relative">
                      <User className="absolute left-3 top-2.5 w-4 h-4 text-slate-400" />
                      <input
                        type="text"
                        placeholder="John Doe"
                        required
                        value={fullName}
                        onChange={(e) => setFullName(e.target.value)}
                        className="w-full pl-9 pr-3 py-1.5 bg-slate-50 border border-slate-200 focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500/20 rounded-lg text-slate-900 placeholder-slate-400 transition outline-none text-xs"
                        id="reg-fullname"
                      />
                    </div>
                  </div>

                  <div>
                    <label className="block text-[11px] font-semibold text-slate-500 uppercase tracking-wider mb-1">
                      Registering As
                    </label>
                    <div className="grid grid-cols-2 gap-2" id="role-selector">
                      <button
                        type="button"
                        onClick={() => setRole(UserRole.CANDIDATE)}
                        className={`py-1.5 px-3 border rounded-lg text-xs font-semibold flex items-center justify-center gap-1.5 transition cursor-pointer ${role === UserRole.CANDIDATE ? "border-indigo-600 bg-indigo-50/50 text-indigo-700" : "border-slate-200 bg-slate-50 text-slate-500 hover:text-slate-800"}`}
                        id="role-cand-trigger"
                      >
                        <User className="w-3.5 h-3.5" />
                        <span>Candidate</span>
                      </button>
                      <button
                        type="button"
                        onClick={() => setRole(UserRole.RECRUITER)}
                        className={`py-1.5 px-3 border rounded-lg text-xs font-semibold flex items-center justify-center gap-1.5 transition cursor-pointer ${role === UserRole.RECRUITER ? "border-indigo-600 bg-indigo-50/50 text-indigo-700" : "border-slate-200 bg-slate-50 text-slate-500 hover:text-slate-800"}`}
                        id="role-rec-trigger"
                      >
                        <Building2 className="w-3.5 h-3.5" />
                        <span>Recruiter</span>
                      </button>
                    </div>
                  </div>

                  {role === UserRole.RECRUITER && (
                    <div>
                      <label className="block text-[11px] font-semibold text-slate-500 uppercase tracking-wider mb-1">
                        Company Name
                      </label>
                      <div className="relative">
                        <Building2 className="absolute left-3 top-2.5 w-4 h-4 text-slate-400" />
                        <input
                          type="text"
                          placeholder="e.g. Acme Tech Labs"
                          required
                          value={companyName}
                          onChange={(e) => setCompanyName(e.target.value)}
                          className="w-full pl-9 pr-3 py-1.5 bg-slate-50 border border-slate-200 focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500/20 rounded-lg text-slate-900 placeholder-slate-400 transition outline-none text-xs"
                          id="reg-company"
                        />
                      </div>
                    </div>
                  )}
                </>
              )}

              <div>
                <label className="block text-[11px] font-semibold text-slate-500 uppercase tracking-wider mb-1">
                  Email Address
                </label>
                <div className="relative">
                  <Mail className="absolute left-3 top-2.5 w-4 h-4 text-slate-400" />
                  <input
                     type="email"
                     placeholder="you@example.com"
                     required
                     value={email}
                     onChange={(e) => setEmail(e.target.value)}
                     className="w-full pl-9 pr-3 py-1.5 bg-slate-50 border border-slate-200 focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500/20 rounded-lg text-slate-900 placeholder-slate-400 transition outline-none text-xs"
                     id="credentials-email"
                  />
                </div>
              </div>

              <div>
                <label className="block text-[11px] font-semibold text-slate-500 uppercase tracking-wider mb-1">
                  Password
                </label>
                <div className="relative">
                  <Lock className="absolute left-3 top-2.5 w-4 h-4 text-slate-400" />
                  <input
                    type="password"
                    placeholder="••••••••"
                    required
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    className="w-full pl-9 pr-3 py-1.5 bg-slate-50 border border-slate-200 focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500/20 rounded-lg text-slate-900 placeholder-slate-400 transition outline-none text-xs"
                    id="credentials-pass"
                  />
                </div>
              </div>

              <button
                type="submit"
                disabled={loading}
                className="w-full py-2 bg-indigo-600 hover:bg-indigo-700 active:bg-indigo-800 disabled:opacity-50 text-white font-bold rounded-lg transition cursor-pointer text-xs mt-3 shadow-xs"
                id="submit-auth-btn"
              >
                {loading ? "Authenticating Session..." : isLogin ? "Access Portal Dashboard" : "Register and Continue"}
              </button>
            </form>
          </div>
        </div>
      </main>

      <footer className="w-full text-center text-slate-400 text-xs py-4 border-t border-slate-200 mt-auto bg-white" id="auth-footer">
        © 2026 SaaS Technical Screening Platform. Compliance metrics SOC 2, ISO 27001, GDPR certified.
      </footer>
    </div>
  );
}
